"""Rebuild Geneva canton from preserved INSEE, FSO and OCSTAT source snapshots."""
import csv
import json
from pathlib import Path
import re
import unicodedata
from collections import defaultdict

root = Path(__file__).resolve().parents[1]
sources = root / 'audits/2026-09-06/sources'
points = json.loads((root / 'app/data/commune-centres.json').read_text())
insee = json.loads((sources / 'insee-swiss-aggregates.json').read_text())


def normalise(name):
    name = re.sub(r'\s*\([A-Z]{2}\)$', '', name.upper())
    return re.sub('[^A-Z]', '', unicodedata.normalize('NFKD', name).encode('ascii', 'ignore').decode())


def allocate(values, target):
    total = sum(values.values())
    assert total > 0
    exact = {k: v * target / total for k, v in values.items()}
    result = {k: int(v) for k, v in exact.items()}
    for k in sorted(exact, key=lambda k: exact[k] - result[k], reverse=True)[:target - sum(result.values())]:
        result[k] += 1
    assert sum(result.values()) == target
    return result


def point(code):
    c, name, lat, lon = points[code]
    return dict(code=c, name=name, lat=lat, lon=lon)


names = {normalise(p[1]): p[0] for p in points.values() if p[0].startswith('CH66')}
destinations = {d['code']: names[normalise(d['name'])] for d in insee['destinations'] if d['code'].startswith('SUC')}
assert len(destinations) == 45
french = defaultdict(float)
excluded_no_journey = 0
for row in insee['rows']:
    if not re.match(r'^FR(01|74)', row['origin']) or row['destination'] not in destinations:
        continue
    if row['trans'] == '1':
        excluded_no_journey += row['people']
        continue
    mode = {'2': 'soft', '3': 'soft', '4': 'car', '5': 'car', '6': 'transit'}[row['trans']]
    french[(row['origin'], destinations[row['destination']], mode)] += row['people']

swiss = {'inbound': defaultdict(int), 'outbound': defaultdict(int)}
with (sources / 'fso-commune-matrix-original').open(encoding='utf-8-sig', newline='') as f:
    for row in csv.DictReader(f):
        if row['REF_YEAR'] != '2020':
            continue
        direction = ('inbound' if row['PERSPECTIVE'] == 'W' and row['GEO_CANT_RESID'] == '22' and row['GEO_CANT_WORK'] == '25'
                     else 'outbound' if row['PERSPECTIVE'] == 'R' and row['GEO_CANT_RESID'] == '25' and row['GEO_CANT_WORK'] == '22' else None)
        if direction:
            swiss[direction][('CH' + row['GEO_COMM_RESID'], 'CH' + row['GEO_COMM_WORK'])] += int(row['VALUE'])

raw = []
unlocated = defaultdict(int)
# OCSTAT 2024, Vaud-only in both directions. The mixed foreign/unknown remainder is not assigned to Swiss routes.
for direction, total in [('inbound', 23398), ('outbound', 6881)]:
    for (origin, target), people in allocate(swiss[direction], total).items():
        if people:
            if origin not in points or target not in points:
                unlocated[direction] += people
                continue
            raw.append([point(origin), point(target), people, direction])
observed = []
for (origin, target, mode), weighted in sorted(french.items()):
    people = int(weighted + 0.5)
    if people:
        observed.append(dict(origin=point(origin), target=point(target), commuters=people, mode=mode,
                             direction='inbound', source='INSEE RP2023 / reported workplace commune and mode'))
summary = dict(frenchCommuters2023=sum(c['commuters'] for c in observed), vaudToGeneva2024=23398,
               genevaToVaud2024=6881, excludedNoJourney2023=excluded_no_journey,
               unmappedOtherInbound2024=2230, unmappedOtherOrUnknownOutbound2024=1822,
               frenchWorkplaceCommunes=len(destinations), modeYear=2023)
summary.update(mappedVaudToGeneva2024=23398 - unlocated['inbound'], mappedGenevaToVaud2024=6881 - unlocated['outbound'])
text = "// Generated by scripts/generate-geneva-data.py. Geography: Geneva canton; Swiss flows: Vaud only.\n"
text += "import type { Corridor, Point } from './types.ts';\nimport { commuteModeShares, splitModes } from './create-city-data.ts';\n"
text += 'const swissPairs: Array<[Point, Point, number, "inbound" | "outbound"]> = ' + json.dumps(raw, ensure_ascii=False) + ';\n'
text += 'const french: Corridor[] = ' + json.dumps(observed, ensure_ascii=False) + ';\n'
text += "export const corridors: Corridor[] = [...swissPairs.flatMap(([origin, target, people, direction]) => splitModes(people, commuteModeShares(origin, target)).map(([mode, commuters]) => ({ origin, target, commuters, direction, mode, source: 'FSO 2020 OD / OCSTAT Vaud totals 2024 / OCT commuting modes 2020' }))), ...french];\n"
text += 'export const dataSummary = { ...' + json.dumps(summary) + ', corridors: corridors.length, originCommunes: new Set(corridors.map(c => c.direction === "inbound" ? c.origin.code : c.target.code)).size };\n'
(root / 'app/data/geneva.ts').write_text(text)
print(json.dumps(dict(swissPairs=len(raw), frenchPairs=len(observed), **summary)))
